### ISSUE TITLE
Chercher et intégrer de nouveaux "fonts"

### ISSUE THREAD

**Issue by atcheri** [masahiroendo/or-argent#3]
- [x] Effectuer des recherches sur des sites de fonts gratuits (ex: [google fonts](https://fonts.google.com/), [dafonts](https://www.dafont.com/fr/), [fontspace](https://www.fontspace.com/new/fonts) ...)
- [x] Une fois trouvé, intégrer les fonts via chakra-ui ([how to](https://chakra-ui.com/docs/styled-system/recipes/using-fonts))
- [x] Définir éventuellement un component qui va se utiliser ces fonts pour créer des h1 h2 h3 ... (idée à créuser)

**Comment by masahiroendo** [comment]
Utlisation de Playfair Display de google fonts.
