### ISSUE TITLE
Affichage des prix, variations en couleur

### ISSUE THREAD

**Issue by atcheri** [masahiroendo/or-argent#5]
A l'image de ce qui se fait sur or.fr, on se propose ici d'afficher les variations positives en vert et les négatives en rouge, ainsi que leur icons flĉhes correspondantes.

![image](https://user-images.githubusercontent.com/1909176/167267875-a6a76338-b4d0-41e1-9dc5-840e69d59ca1.png)

Une fois le format de la réponse de l'api définie, on pourrait utiliser une fake api (locale) qui s'appelle [msw](https://mswjs.io/docs/getting-started/integrate/node)

**Comment by masahiroendo** [comment]
style ajoué via scss
